//
//  RealisticNotificationData.swift
//  FPLMonitor
//
//  Realistic notification data with current Premier League players
//

import Foundation

struct RealisticNotificationData {
    
    static let sampleNotifications: [FPLNotification] = [
        // GOALS
        FPLNotification(
            title: "⚽ Goal!",
            body: "Mohamed Salah scored for Liverpool",
            type: .goals,
            player: "Mohamed Salah",
            team: "Liverpool",
            teamAbbreviation: "LIV",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Goal",
            totalPoints: 89,
            gameweekPoints: 8,
            gameweek: 15,
            overallOwnership: 45.2,
            isOwned: true,
            timestamp: Date(),
            homeTeam: "Liverpool",
            awayTeam: "Arsenal",
            fixture: "LIV vs ARS",
            impact: .high
        ),
        
        FPLNotification(
            title: "⚽ Goal!",
            body: "Erling Haaland scored for Manchester City",
            type: .goals,
            player: "Erling Haaland",
            team: "Manchester City",
            teamAbbreviation: "MCI",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Goal",
            totalPoints: 76,
            gameweekPoints: 6,
            gameweek: 15,
            overallOwnership: 52.8,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .hour, value: -1, to: Date()) ?? Date(),
            homeTeam: "Manchester City",
            awayTeam: "Chelsea",
            fixture: "MCI vs CHE",
            impact: .high
        ),
        
        FPLNotification(
            title: "⚽ Goal!",
            body: "Jean-Philippe Mateta scored for Crystal Palace",
            type: .goals,
            player: "Jean-Philippe Mateta",
            team: "Crystal Palace",
            teamAbbreviation: "CRY",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Goal",
            totalPoints: 34, gameweekPoints: 2, gameweek: 15,
            overallOwnership: 8.7,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .hour, value: -2, to: Date()) ?? Date(),
            homeTeam: "Crystal Palace",
            awayTeam: "Brighton",
            fixture: "CRY vs BHA",
            impact: .medium
        ),
        
        FPLNotification(
            title: "⚽ Goal!",
            body: "Ollie Watkins scored for Aston Villa",
            type: .goals,
            player: "Ollie Watkins",
            team: "Aston Villa",
            teamAbbreviation: "AVL",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Goal",
            totalPoints: 67, gameweekPoints: 7, gameweek: 15,
            overallOwnership: 28.4,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .hour, value: -3, to: Date()) ?? Date(),
            homeTeam: "Aston Villa",
            awayTeam: "Newcastle",
            fixture: "AVL vs NEW",
            impact: .high
        ),
        
        // ASSISTS
        FPLNotification(
            title: "🎯 Assist!",
            body: "Kaoru Mitoma provided an assist",
            type: .assists,
            player: "Kaoru Mitoma",
            team: "Brighton",
            teamAbbreviation: "BHA",
            points: 3,
            pointsChange: +3,
            pointsCategory: "Assist",
            totalPoints: 42, gameweekPoints: 4, gameweek: 15,
            overallOwnership: 12.3,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .hour, value: -4, to: Date()) ?? Date(),
            homeTeam: "Brighton",
            awayTeam: "Crystal Palace",
            fixture: "BHA vs CRY",
            impact: .medium
        ),
        
        FPLNotification(
            title: "🎯 Assist!",
            body: "Bukayo Saka provided an assist",
            type: .assists,
            player: "Bukayo Saka",
            team: "Arsenal",
            teamAbbreviation: "ARS",
            points: 3,
            pointsChange: +3,
            pointsCategory: "Assist",
            totalPoints: 71, gameweekPoints: 8, gameweek: 15,
            overallOwnership: 38.9,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .hour, value: -5, to: Date()) ?? Date(),
            homeTeam: "Arsenal",
            awayTeam: "Liverpool",
            fixture: "ARS vs LIV",
            impact: .high
        ),
        
        FPLNotification(
            title: "🎯 Assist!",
            body: "Cole Palmer provided an assist",
            type: .assists,
            player: "Cole Palmer",
            team: "Chelsea",
            teamAbbreviation: "CHE",
            points: 3,
            pointsChange: +3,
            pointsCategory: "Assist",
            totalPoints: 58, gameweekPoints: 5, gameweek: 15,
            overallOwnership: 24.6,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .hour, value: -6, to: Date()) ?? Date(),
            homeTeam: "Chelsea",
            awayTeam: "Manchester City",
            fixture: "CHE vs MCI",
            impact: .medium
        ),
        
        // CLEAN SHEETS
        FPLNotification(
            title: "🛡️ Clean Sheet!",
            body: "Alisson kept a clean sheet",
            type: .cleanSheets,
            player: "Alisson",
            team: "Liverpool",
            teamAbbreviation: "LIV",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Clean Sheet",
            totalPoints: 45, gameweekPoints: 5, gameweek: 15,
            overallOwnership: 18.7,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date(),
            homeTeam: "Liverpool",
            awayTeam: "Arsenal",
            fixture: "LIV vs ARS",
            impact: .medium
        ),
        
        FPLNotification(
            title: "🛡️ Clean Sheet!",
            body: "Guglielmo Vicario kept a clean sheet",
            type: .cleanSheets,
            player: "Guglielmo Vicario",
            team: "Tottenham",
            teamAbbreviation: "TOT",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Clean Sheet",
            totalPoints: 38, gameweekPoints: 2, gameweek: 15,
            overallOwnership: 9.2,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date(),
            homeTeam: "Tottenham",
            awayTeam: "West Ham",
            fixture: "TOT vs WHU",
            impact: .medium
        ),
        
        FPLNotification(
            title: "🛡️ Clean Sheet!",
            body: "William Saliba kept a clean sheet",
            type: .cleanSheets,
            player: "William Saliba",
            team: "Arsenal",
            teamAbbreviation: "ARS",
            points: 4,
            pointsChange: +4,
            pointsCategory: "Clean Sheet",
            totalPoints: 52, gameweekPoints: 6, gameweek: 15,
            overallOwnership: 31.4,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date(),
            homeTeam: "Arsenal",
            awayTeam: "Liverpool",
            fixture: "ARS vs LIV",
            impact: .high
        ),
        
        // BONUS POINTS
        FPLNotification(
            title: "⭐ Bonus Points!",
            body: "Declan Rice earned 3 bonus points",
            type: .bonus,
            player: "Declan Rice",
            team: "Arsenal",
            teamAbbreviation: "ARS",
            points: 3,
            pointsChange: +3,
            pointsCategory: "Bonus",
            totalPoints: 49, gameweekPoints: 5, gameweek: 15,
            overallOwnership: 22.1,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date(),
            homeTeam: "Arsenal",
            awayTeam: "Liverpool",
            fixture: "ARS vs LIV",
            impact: .medium
        ),
        
        FPLNotification(
            title: "⭐ Bonus Points!",
            body: "Phil Foden earned 2 bonus points",
            type: .bonus,
            player: "Phil Foden",
            team: "Manchester City",
            teamAbbreviation: "MCI",
            points: 2,
            pointsChange: +2,
            pointsCategory: "Bonus",
            totalPoints: 63, gameweekPoints: 7, gameweek: 15,
            overallOwnership: 26.8,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date(),
            homeTeam: "Manchester City",
            awayTeam: "Chelsea",
            fixture: "MCI vs CHE",
            impact: .medium
        ),
        
        // YELLOW CARDS
        FPLNotification(
            title: "🟡 Yellow Card",
            body: "Bruno Fernandes received a yellow card",
            type: .yellowCards,
            player: "Bruno Fernandes",
            team: "Manchester United",
            teamAbbreviation: "MUN",
            points: -1,
            pointsChange: -1,
            pointsCategory: "Yellow Card",
            totalPoints: 41,
            gameweekPoints: 6,
            gameweek: 3,
            overallOwnership: 15.3,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -2, to: Date()) ?? Date(),
            homeTeam: "Manchester United",
            awayTeam: "Everton",
            fixture: "MUN vs EVE",
            impact: .low
        ),
        
        FPLNotification(
            title: "🟡 Yellow Card",
            body: "João Palhinha received a yellow card",
            type: .yellowCards,
            player: "João Palhinha",
            team: "Fulham",
            teamAbbreviation: "FUL",
            points: -1,
            pointsChange: -1,
            pointsCategory: "Yellow Card",
            totalPoints: 28,
            gameweekPoints: 4,
            gameweek: 3,
            overallOwnership: 6.7,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -2, to: Date()) ?? Date(),
            homeTeam: "Fulham",
            awayTeam: "Brentford",
            fixture: "FUL vs BRE",
            impact: .low
        ),
        
        // RED CARDS
        FPLNotification(
            title: "🔴 Red Card",
            body: "Trevoh Chalobah received a red card",
            type: .redCards,
            player: "Trevoh Chalobah",
            team: "Chelsea",
            teamAbbreviation: "CHE",
            points: -3,
            pointsChange: -3,
            pointsCategory: "Red Card",
            totalPoints: 19,
            gameweekPoints: 2,
            gameweek: 3,
            overallOwnership: 3.2,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -2, to: Date()) ?? Date(),
            homeTeam: "Chelsea",
            awayTeam: "Manchester City",
            fixture: "CHE vs MCI",
            impact: .high
        ),
        
        // SAVES
        FPLNotification(
            title: "💪 Saves!",
            body: "Jordan Pickford made 6 saves",
            type: .saves,
            player: "Jordan Pickford",
            team: "Everton",
            teamAbbreviation: "EVE",
            points: 2,
            pointsChange: +2,
            pointsCategory: "Saves",
            totalPoints: 33, gameweekPoints: 2, gameweek: 15,
            overallOwnership: 7.8,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -2, to: Date()) ?? Date(),
            homeTeam: "Everton",
            awayTeam: "Manchester United",
            fixture: "EVE vs MUN",
            impact: .medium
        ),
        
        FPLNotification(
            title: "💪 Saves!",
            body: "André Onana made 4 saves",
            type: .saves,
            player: "André Onana",
            team: "Manchester United",
            teamAbbreviation: "MUN",
            points: 1,
            pointsChange: +1,
            pointsCategory: "Saves",
            totalPoints: 29, gameweekPoints: 2, gameweek: 15,
            overallOwnership: 11.4,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -2, to: Date()) ?? Date(),
            homeTeam: "Manchester United",
            awayTeam: "Everton",
            fixture: "MUN vs EVE",
            impact: .low
        ),
        
        // GOALS CONCEDED
        FPLNotification(
            title: "😞 Goals Conceded",
            body: "Ederson conceded 2 goals",
            type: .goalsConceded,
            player: "Ederson",
            team: "Manchester City",
            teamAbbreviation: "MCI",
            points: -2,
            pointsChange: -2,
            pointsCategory: "Goals Conceded",
            totalPoints: 31,
            gameweekPoints: 3,
            gameweek: 3,
            overallOwnership: 14.6,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -3, to: Date()) ?? Date(),
            homeTeam: "Manchester City",
            awayTeam: "Chelsea",
            fixture: "MCI vs CHE",
            impact: .medium
        ),
        
        // PENALTY MISSED
        FPLNotification(
            title: "❌ Penalty Missed",
            body: "Ivan Toney missed a penalty",
            type: .penaltyMissed,
            player: "Ivan Toney",
            team: "Brentford",
            teamAbbreviation: "BRE",
            points: -2,
            pointsChange: -2,
            pointsCategory: "Penalty Missed",
            totalPoints: 25,
            gameweekPoints: 3,
            gameweek: 3,
            overallOwnership: 8.9,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -3, to: Date()) ?? Date(),
            homeTeam: "Brentford",
            awayTeam: "Fulham",
            fixture: "BRE vs FUL",
            impact: .high
        ),
        
        // PENALTY SAVED
        FPLNotification(
            title: "🥅 Penalty Saved!",
            body: "Nick Pope saved a penalty",
            type: .penaltySaved,
            player: "Nick Pope",
            team: "Newcastle",
            teamAbbreviation: "NEW",
            points: 5,
            pointsChange: +5,
            pointsCategory: "Penalty Saved",
            totalPoints: 36, gameweekPoints: 2, gameweek: 15,
            overallOwnership: 9.1,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -3, to: Date()) ?? Date(),
            homeTeam: "Newcastle",
            awayTeam: "Aston Villa",
            fixture: "NEW vs AVL",
            impact: .high
        ),
        
        // OWN GOALS
        FPLNotification(
            title: "😱 Own Goal",
            body: "Marc Guéhi scored an own goal",
            type: .ownGoals,
            player: "Marc Guéhi",
            team: "Crystal Palace",
            teamAbbreviation: "CRY",
            points: -2,
            pointsChange: -2,
            pointsCategory: "Own Goal",
            totalPoints: 22,
            gameweekPoints: 1,
            gameweek: 3,
            overallOwnership: 4.3,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -4, to: Date()) ?? Date(),
            isRead: false,
            homeTeam: "Crystal Palace",
            awayTeam: "Brighton",
            fixture: "CRY vs BHA",
            impact: .high
        ),
        
        // DEFENSIVE CONTRIBUTION
        FPLNotification(
            title: "🛡️ DEFCON!",
            body: "Virgil van Dijk made key defensive contributions",
            type: .defensiveContribution,
            player: "Virgil van Dijk",
            team: "Liverpool",
            teamAbbreviation: "LIV",
            points: 1,
            pointsChange: +1,
            pointsCategory: "DEFCON",
            totalPoints: 47, gameweekPoints: 5, gameweek: 15,
            overallOwnership: 19.7,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -4, to: Date()) ?? Date(),
            homeTeam: "Liverpool",
            awayTeam: "Arsenal",
            fixture: "LIV vs ARS",
            impact: .low
        ),
        
        // PRICE CHANGES
        FPLNotification(
            title: "💰 Price Change!",
            body: "Jarrod Bowen's price increased to £7.2m",
            type: .priceChanges,
            player: "Jarrod Bowen",
            team: "West Ham",
            teamAbbreviation: "WHU",
            points: 0,
            pointsChange: 0,
            pointsCategory: "Price Rise",
            totalPoints: 44, gameweekPoints: 4, gameweek: 15,
            overallOwnership: 13.2,
            isOwned: false,
            timestamp: Calendar.current.date(byAdding: .day, value: -5, to: Date()) ?? Date(),
            homeTeam: "West Ham",
            awayTeam: "Tottenham",
            fixture: "WHU vs TOT",
            impact: .low,
            playerPrice: 7.2,
            priceChange: 0.1
        ),
        
        FPLNotification(
            title: "💰 Price Change!",
            body: "Marcus Rashford's price decreased to £8.4m",
            type: .priceChanges,
            player: "Marcus Rashford",
            team: "Manchester United",
            teamAbbreviation: "MUN",
            points: 0,
            pointsChange: 0,
            pointsCategory: "Price Fall",
            totalPoints: 38, gameweekPoints: 1, gameweek: 15,
            overallOwnership: 28.5,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -3, to: Date()) ?? Date(),
            homeTeam: "Manchester United",
            awayTeam: "Brighton",
            fixture: "MUN vs BHA",
            impact: .medium,
            playerPrice: 8.4,
            priceChange: -0.1
        ),
        
        // STATUS CHANGES
        FPLNotification(
            title: "📊 Status Change",
            body: "Dominic Solanke is now available",
            type: .statusChanges,
            player: "Dominic Solanke",
            team: "Bournemouth",
            teamAbbreviation: "BOU",
            points: 0,
            pointsChange: 0,
            pointsCategory: "Available",
            totalPoints: 39, gameweekPoints: 2, gameweek: 15,
            overallOwnership: 6.8,
            isOwned: true,
            timestamp: Calendar.current.date(byAdding: .day, value: -5, to: Date()) ?? Date(),
            homeTeam: "Bournemouth",
            awayTeam: "Wolves",
            fixture: "BOU vs WOL",
            impact: .medium
        )
    ]
}
