#!/bin/bash
# Simple deployment script for DigitalOcean droplet

DROPLET_IP="138.68.28.59"

echo "🚀 Simple FPL Monitor Deployment"
echo "📍 Droplet IP: $DROPLET_IP"
echo ""
echo "📋 Manual Steps Required:"
echo "1. SSH into your droplet: ssh root@$DROPLET_IP"
echo "2. Run these commands on the droplet:"
echo ""
echo "   # Update system"
echo "   apt update && apt install -y python3 python3-pip python3-venv git"
echo ""
echo "   # Clone your project (you'll need to push to GitHub first)"
echo "   git clone https://github.com/yourusername/fpl-monitor.git"
echo "   cd fpl-monitor"
echo ""
echo "   # Install dependencies"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install fastapi uvicorn requests psycopg2-binary python-dotenv pytz websockets"
echo ""
echo "   # Create .env file with your Supabase credentials"
echo "   nano .env"
echo ""
echo "   # Start the service"
echo "   python3 backend/services/fpl_monitor_simple.py"
echo ""
echo "🌐 After setup, service will run on: http://$DROPLET_IP:8000"
